CREATE TABLE op_products
(
	id_product INT NOT NULL AUTO_INCREMENT,
	description VARCHAR(200) NOT NULL DEFAULT '',
	quick_code VARCHAR(200) NOT NULL DEFAULT '',
	id_type INT NOT NULL DEFAULT 0,
	id_provider INT NOT NULL DEFAULT 0,
	id_category INT NOT NULL DEFAULT 0,
	id_unity INT NOT NULL DEFAULT 0,
	sales_price DECIMAL(18,2) NOT NULL DEFAULT (18,2),
	employed_price DECIMAL(18,2) NOT NULL DEFAULT (18,2),
	shop_price DECIMAL(18,2) NOT NULL DEFAULT (18,2),
	id_iva DECIMAL(18,2) NOT NULL DEFAULT (18,2),
	id_has_IEPS INT NOT NULL DEFAULT 0,
	IEPS DECIMAL(18,2) NOT NULL DEFAULT (18,2),
	id_warehouse INT NOT NULL DEFAULT 0,
	status INT NOT NULL DEFAULT 0,
	created_by INT NOT NULL DEFAULT 0,
	updated_by INT NOT NULL DEFAULT 0,
	created_at DATETIME NOT NULL DEFAULT NOW(),
	updated_at DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (id_product)
)